### ISSUE TITLE
you can increase the use of wmi example

### ISSUE THREAD

**Issue by CodyGuo** [gabriel-samfira/go-wmi#2]
How to use wmi query？
How to use wmi set IP？

**Comment by gabriel-samfira** [comment]
here you go:

https://github.com/gabriel-samfira/go-wmi/commit/4e1203cad7cc77c88ceb2d9a9a00e04b47b4aa7d

Note...this project is just an experiment. Not meant for any type of real use.

**Comment by CodyGuo** [comment]
Ok, thank you.
I'm learning wmi
